version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: host
    volumes:
      - /yourpath/config:/config
      - /yourpath/Jellyfin/cache:/cache
      - /yourpath/Jellyfin/media:/media
    restart: unless-stopped
