---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: audibookshelf
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helmcharts/AudioBookShelf/
      version: 1.0.0
      sourceRef:
        kind: GitRepository
        name: homeserver
        namespace: flux-system
      interval: 1m0s
