version: '3'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=9091
    ports:
      - "9091:9091"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - /mnt/raid1/qbittorrent/appdata/config:/config
      - /mnt/raid1/qbittorrent/downloads:/downloads
    restart: unless-stopped
