version: '3'
services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - "9000:80"
    volumes:
      - /mnt/raid1/nextcloud/html:/var/www/html
      - /mnt/raid1/nextcloud/apps:/var/www/html/custom_apps
      - /mnt/raid1/nextcloud/config:/var/www/html/config
      - /mnt/raid1/nextcloud/data:/var/www/html/data
      - /mnt/raid1/nextcloud/theme:/var/www/html/themes
    restart: unless-stopped
